# This is a config for Novita Agent Sandbox template.
# You can use template ID (w96zzh126o6bi98pxfcs) to create a sandbox:

# Python SDK
# from novita_sandbox.core import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("w96zzh126o6bi98pxfcs") # Sync sandbox
# sandbox = await AsyncSandbox.create("w96zzh126o6bi98pxfcs") # Async sandbox

# JS SDK
# import { Sandbox } from 'novita-sandbox'
# const sandbox = await Sandbox.create('w96zzh126o6bi98pxfcs')

team_id = "e08268b2-dafb-4723-83ad-04636dc4556e"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "novita.Dockerfile"
template_id = "w96zzh126o6bi98pxfcs"
